# Custom Language File for Launcher Customizer

[ejs.app]
title = "FoxDeath Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/F0xenn/FoxdeathLauncher"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/CnKEKee"

[ejs.settings]
sourceGithubLink = "https://github.com/F0xenn/FoxdeathLauncher"
supportLink = "https://github.com/F0xenn/FoxdeathLauncher/issues"

[ejs.welcome]
welcomeHeader = "Bienvenue sur FoxDeath"
welcomeDescription = "S'amusez c'est surtout ça !"
welcomeDescCTA = "et s'amusez aussi XD"
